@tool
extends EditorPlugin

## Registers our Android manifest tweaks (see export_plugin.gd) so they apply on every export.
## Committed on purpose: res://android/ is gitignored and regenerated by "Install Android Build
## Template", so a manual manifest edit there would not survive. An export plugin does.
## Also registers the Web-export file copy (see web_export_plugin.gd).

var _exporter: EditorExportPlugin
var _web_exporter: EditorExportPlugin


func _enter_tree() -> void:
	_exporter = preload("res://addons/limpid_export/export_plugin.gd").new()
	add_export_plugin(_exporter)
	_web_exporter = preload("res://addons/limpid_export/web_export_plugin.gd").new()
	add_export_plugin(_web_exporter)


func _exit_tree() -> void:
	if _exporter != null:
		remove_export_plugin(_exporter)
		_exporter = null
	if _web_exporter != null:
		remove_export_plugin(_web_exporter)
		_web_exporter = null
